version: '3.8'

services:
  directus:
    image: directus/directus:latest
    ports:
      - "${PORT:-8055}:8055"
    environment:
      KEY: value
    volumes:
      - ./uploads:/directus/uploads
      - ./database:/directus/database
    restart: unless-stopped
